### ISSUE TITLE
Updated release to Docker Hub

### ISSUE THREAD

**Issue by kenjones-cisco** [uzyexe/dockerfile-terraform#2]
According to Docker Hub the repository is automated build but the latest changes are still not showing up there.

Is it possible to push an updated version to Docker Hub?

**Comment by uzyexe** [comment]
Hi, @kenjones-cisco 

I ran the automated build. now.
has been updated to the latest build.

thank you!

**Comment by kenjones-cisco** [comment]
Thanks!
